# Generated by Django 3.1.3 on 2020-11-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Direcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Edad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Sexo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Telefono',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='Tratamiento',
            field=models.CharField(max_length=50),
        ),
    ]
