# Generated by Django 3.1.3 on 2020-11-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0002_auto_20201115_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='avances'),
        ),
    ]
