# Generated by Django 3.1.3 on 2020-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0003_tratamiento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Perfiles/avances'),
        ),
    ]
