# Generated by Django 3.1.3 on 2020-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0004_auto_20201115_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Perfiles'),
        ),
    ]
