# Generated by Django 3.1.3 on 2020-11-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0006_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='Informacion_Adicional',
        ),
        migrations.AddField(
            model_name='datos',
            name='Padece_de_alguna_enfermedad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos',
            name='Toma_algun_tipo_de_medicamento',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Fecha_de_consulta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='Descripcion',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='Fecha_de_cita',
            field=models.DateField(max_length=50),
        ),
    ]
