# Generated by Django 3.1.3 on 2020-11-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0007_auto_20201115_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='Informacion_Adicional_Sobre_el_paciente',
            field=models.TextField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
